{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "644fb9c6-6fe4-4716-a8fa-1c2401e87c3b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting fastapi\n",
      "  Downloading fastapi-0.115.11-py3-none-any.whl.metadata (27 kB)\n",
      "Collecting uvicorn\n",
      "  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)\n",
      "Collecting starlette<0.47.0,>=0.40.0 (from fastapi)\n",
      "  Downloading starlette-0.46.1-py3-none-any.whl.metadata (6.2 kB)\n",
      "Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from fastapi) (2.3.0)\n",
      "Collecting typing-extensions>=4.8.0 (from fastapi)\n",
      "  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from uvicorn) (8.1.7)\n",
      "Collecting h11>=0.8 (from uvicorn)\n",
      "  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from click>=7.0->uvicorn) (0.4.6)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.5.0)\n",
      "Requirement already satisfied: pydantic-core==2.6.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.6.3)\n",
      "Requirement already satisfied: anyio<5,>=3.6.2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from starlette<0.47.0,>=0.40.0->fastapi) (4.0.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (3.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (1.3.0)\n",
      "Downloading fastapi-0.115.11-py3-none-any.whl (94 kB)\n",
      "Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)\n",
      "Downloading h11-0.14.0-py3-none-any.whl (58 kB)\n",
      "Downloading starlette-0.46.1-py3-none-any.whl (71 kB)\n",
      "Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)\n",
      "Installing collected packages: typing-extensions, h11, uvicorn, starlette, fastapi\n",
      "  Attempting uninstall: typing-extensions\n",
      "    Found existing installation: typing_extensions 4.5.0\n",
      "    Uninstalling typing_extensions-4.5.0:\n",
      "      Successfully uninstalled typing_extensions-4.5.0\n",
      "Successfully installed fastapi-0.115.11 h11-0.14.0 starlette-0.46.1 typing-extensions-4.12.2 uvicorn-0.34.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorflow-intel 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.12.2 which is incompatible.\n"
     ]
    }
   ],
   "source": [
    "pip install fastapi uvicorn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c07ff123-195b-438e-be97-b6a980e97de0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: transformers in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (4.41.0)\n",
      "Collecting datasets\n",
      "  Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: filelock in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (3.12.4)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.23.0)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (1.23.5)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (23.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (6.0.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2024.5.15)\n",
      "Requirement already satisfied: requests in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2.31.0)\n",
      "Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.19.1)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.4.3)\n",
      "Requirement already satisfied: tqdm>=4.27 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (4.66.1)\n",
      "Collecting pyarrow>=15.0.0 (from datasets)\n",
      "  Downloading pyarrow-19.0.1-cp311-cp311-win_amd64.whl.metadata (3.4 kB)\n",
      "Collecting dill<0.3.9,>=0.3.0 (from datasets)\n",
      "  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)\n",
      "Requirement already satisfied: pandas in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (1.5.3)\n",
      "Collecting requests (from transformers)\n",
      "  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)\n",
      "Collecting tqdm>=4.27 (from transformers)\n",
      "  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)\n",
      "Collecting xxhash (from datasets)\n",
      "  Downloading xxhash-3.5.0-cp311-cp311-win_amd64.whl.metadata (13 kB)\n",
      "Collecting multiprocess<0.70.17 (from datasets)\n",
      "  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)\n",
      "Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.5.0)\n",
      "Collecting aiohttp (from datasets)\n",
      "  Downloading aiohttp-3.11.14-cp311-cp311-win_amd64.whl.metadata (8.0 kB)\n",
      "Collecting huggingface-hub<1.0,>=0.23.0 (from transformers)\n",
      "  Downloading huggingface_hub-0.29.3-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)\n",
      "  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)\n",
      "Collecting aiosignal>=1.1.2 (from aiohttp->datasets)\n",
      "  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (23.1.0)\n",
      "Collecting frozenlist>=1.1.1 (from aiohttp->datasets)\n",
      "  Downloading frozenlist-1.5.0-cp311-cp311-win_amd64.whl.metadata (14 kB)\n",
      "Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)\n",
      "  Downloading multidict-6.2.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)\n",
      "Collecting propcache>=0.2.0 (from aiohttp->datasets)\n",
      "  Downloading propcache-0.3.0-cp311-cp311-win_amd64.whl.metadata (10 kB)\n",
      "Collecting yarl<2.0,>=1.17.0 (from aiohttp->datasets)\n",
      "  Downloading yarl-1.18.3-cp311-cp311-win_amd64.whl.metadata (71 kB)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from huggingface-hub<1.0,>=0.23.0->transformers) (4.12.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (2023.7.22)\n",
      "Requirement already satisfied: colorama in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tqdm>=4.27->transformers) (0.4.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pandas->datasets) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pandas->datasets) (2023.3.post1)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)\n",
      "Downloading datasets-3.4.1-py3-none-any.whl (487 kB)\n",
      "Downloading dill-0.3.8-py3-none-any.whl (116 kB)\n",
      "Downloading aiohttp-3.11.14-cp311-cp311-win_amd64.whl (443 kB)\n",
      "Downloading huggingface_hub-0.29.3-py3-none-any.whl (468 kB)\n",
      "Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)\n",
      "Downloading pyarrow-19.0.1-cp311-cp311-win_amd64.whl (25.3 MB)\n",
      "   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--\n",
      "   ----------- ---------------------------- 7.3/25.3 MB 37.8 MB/s eta 0:00:01\n",
      "   ------------------- -------------------- 12.3/25.3 MB 28.6 MB/s eta 0:00:01\n",
      "   -------------------- ------------------- 13.1/25.3 MB 22.2 MB/s eta 0:00:01\n",
      "   --------------------- ------------------ 13.6/25.3 MB 17.5 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 14.2/25.3 MB 13.9 MB/s eta 0:00:01\n",
      "   ----------------------- ---------------- 14.9/25.3 MB 12.0 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 16.0/25.3 MB 10.8 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 17.3/25.3 MB 10.2 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 18.6/25.3 MB 9.9 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 20.4/25.3 MB 9.6 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 22.3/25.3 MB 9.7 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 24.4/25.3 MB 9.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 25.3/25.3 MB 9.5 MB/s eta 0:00:00\n",
      "Downloading requests-2.32.3-py3-none-any.whl (64 kB)\n",
      "Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)\n",
      "Downloading xxhash-3.5.0-cp311-cp311-win_amd64.whl (30 kB)\n",
      "Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)\n",
      "Downloading aiosignal-1.3.2-py2.py3-none-any.whl (7.6 kB)\n",
      "Downloading frozenlist-1.5.0-cp311-cp311-win_amd64.whl (51 kB)\n",
      "Downloading multidict-6.2.0-cp311-cp311-win_amd64.whl (29 kB)\n",
      "Downloading propcache-0.3.0-cp311-cp311-win_amd64.whl (44 kB)\n",
      "Downloading yarl-1.18.3-cp311-cp311-win_amd64.whl (91 kB)\n",
      "Installing collected packages: xxhash, tqdm, requests, pyarrow, propcache, multidict, frozenlist, dill, aiohappyeyeballs, yarl, multiprocess, huggingface-hub, aiosignal, aiohttp, datasets\n",
      "  Attempting uninstall: tqdm\n",
      "    Found existing installation: tqdm 4.66.1\n",
      "    Uninstalling tqdm-4.66.1:\n",
      "      Successfully uninstalled tqdm-4.66.1\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.31.0\n",
      "    Uninstalling requests-2.31.0:\n",
      "      Successfully uninstalled requests-2.31.0\n",
      "  Attempting uninstall: huggingface-hub\n",
      "    Found existing installation: huggingface-hub 0.23.0\n",
      "    Uninstalling huggingface-hub-0.23.0:\n",
      "      Successfully uninstalled huggingface-hub-0.23.0\n",
      "Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.11.14 aiosignal-1.3.2 datasets-3.4.1 dill-0.3.8 frozenlist-1.5.0 huggingface-hub-0.29.3 multidict-6.2.0 multiprocess-0.70.16 propcache-0.3.0 pyarrow-19.0.1 requests-2.32.3 tqdm-4.67.1 xxhash-3.5.0 yarl-1.18.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorflow-intel 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.12.2 which is incompatible.\n"
     ]
    }
   ],
   "source": [
    "pip install transformers datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b5fd5fb0-83e8-43c0-bbde-5e9bba09250d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: typing_extensions in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (4.12.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade typing_extensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5b6bdea0-ad05-4a71-9c91-bbc812f88cad",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sentence-transformers in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (3.4.1)\n",
      "Requirement already satisfied: transformers in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (4.41.0)\n",
      "Collecting transformers\n",
      "  Downloading transformers-4.50.0-py3-none-any.whl.metadata (39 kB)\n",
      "Requirement already satisfied: datasets in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (3.4.1)\n",
      "Requirement already satisfied: huggingface_hub in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (0.29.3)\n",
      "Requirement already satisfied: tqdm in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sentence-transformers) (4.67.1)\n",
      "Requirement already satisfied: torch>=1.11.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sentence-transformers) (2.0.1)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: scipy in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sentence-transformers) (1.11.2)\n",
      "Requirement already satisfied: Pillow in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sentence-transformers) (10.0.0)\n",
      "Requirement already satisfied: filelock in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (3.12.4)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (1.23.5)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (23.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (6.0.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2024.5.15)\n",
      "Requirement already satisfied: requests in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2.32.3)\n",
      "Collecting tokenizers<0.22,>=0.21 (from transformers)\n",
      "  Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.4.3)\n",
      "Requirement already satisfied: pyarrow>=15.0.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (19.0.1)\n",
      "Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (0.3.8)\n",
      "Requirement already satisfied: pandas in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (1.5.3)\n",
      "Requirement already satisfied: xxhash in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (3.5.0)\n",
      "Requirement already satisfied: multiprocess<0.70.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (0.70.16)\n",
      "Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.5.0)\n",
      "Requirement already satisfied: aiohttp in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from datasets) (3.11.14)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from huggingface_hub) (4.12.2)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (1.3.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (23.1.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (1.5.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (6.2.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (0.3.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from aiohttp->datasets) (1.18.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (2023.7.22)\n",
      "Requirement already satisfied: sympy in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.12)\n",
      "Requirement already satisfied: networkx in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.2)\n",
      "Requirement already satisfied: colorama in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tqdm->sentence-transformers) (0.4.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pandas->datasets) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pandas->datasets) (2023.3.post1)\n",
      "Requirement already satisfied: joblib>=1.1.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from scikit-learn->sentence-transformers) (1.3.2)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from scikit-learn->sentence-transformers) (3.2.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)\n",
      "Requirement already satisfied: mpmath>=0.19 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Downloading transformers-4.50.0-py3-none-any.whl (10.2 MB)\n",
      "   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--\n",
      "   --------------------- ------------------ 5.5/10.2 MB 30.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 10.2/10.2 MB 30.2 MB/s eta 0:00:00\n",
      "Downloading tokenizers-0.21.1-cp39-abi3-win_amd64.whl (2.4 MB)\n",
      "   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--\n",
      "   ----------------- ---------------------- 1.0/2.4 MB 12.7 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 2.1/2.4 MB 6.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.4/2.4 MB 6.3 MB/s eta 0:00:00\n",
      "Installing collected packages: tokenizers, transformers\n",
      "  Attempting uninstall: tokenizers\n",
      "    Found existing installation: tokenizers 0.19.1\n",
      "    Uninstalling tokenizers-0.19.1:\n",
      "      Successfully uninstalled tokenizers-0.19.1\n",
      "  Attempting uninstall: transformers\n",
      "    Found existing installation: transformers 4.41.0\n",
      "    Uninstalling transformers-4.41.0:\n",
      "      Successfully uninstalled transformers-4.41.0\n",
      "Successfully installed tokenizers-0.21.1 transformers-4.50.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: Failed to remove contents in a temporary directory 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~okenizers'.\n",
      "  You can safely remove it manually.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade sentence-transformers transformers datasets huggingface_hub"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "83638b42-4a25-4ae9-94a9-f6deaa6b57d0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: torch in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (2.0.1)\n",
      "Collecting torch\n",
      "  Downloading torch-2.6.0-cp311-cp311-win_amd64.whl.metadata (28 kB)\n",
      "Requirement already satisfied: torchvision in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (0.15.2)\n",
      "Collecting torchvision\n",
      "  Downloading torchvision-0.21.0-cp311-cp311-win_amd64.whl.metadata (6.3 kB)\n",
      "Collecting torchaudio\n",
      "  Downloading torchaudio-2.6.0-cp311-cp311-win_amd64.whl.metadata (6.7 kB)\n",
      "Requirement already satisfied: filelock in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch) (3.12.4)\n",
      "Requirement already satisfied: typing-extensions>=4.10.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch) (4.12.2)\n",
      "Requirement already satisfied: networkx in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch) (3.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch) (3.1.2)\n",
      "Requirement already satisfied: fsspec in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torch) (2024.5.0)\n",
      "Collecting sympy==1.13.1 (from torch)\n",
      "  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from sympy==1.13.1->torch) (1.3.0)\n",
      "Requirement already satisfied: numpy in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torchvision) (1.23.5)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from torchvision) (10.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from jinja2->torch) (2.1.3)\n",
      "Downloading torch-2.6.0-cp311-cp311-win_amd64.whl (204.2 MB)\n",
      "   ---------------------------------------- 0.0/204.2 MB ? eta -:--:--\n",
      "    --------------------------------------- 3.4/204.2 MB 16.7 MB/s eta 0:00:12\n",
      "   - -------------------------------------- 8.1/204.2 MB 20.1 MB/s eta 0:00:10\n",
      "   -- ------------------------------------- 12.3/204.2 MB 20.9 MB/s eta 0:00:10\n",
      "   -- ------------------------------------- 14.9/204.2 MB 18.8 MB/s eta 0:00:11\n",
      "   --- ------------------------------------ 15.7/204.2 MB 16.5 MB/s eta 0:00:12\n",
      "   --- ------------------------------------ 16.3/204.2 MB 13.8 MB/s eta 0:00:14\n",
      "   --- ------------------------------------ 16.8/204.2 MB 12.0 MB/s eta 0:00:16\n",
      "   --- ------------------------------------ 17.6/204.2 MB 10.7 MB/s eta 0:00:18\n",
      "   --- ------------------------------------ 18.6/204.2 MB 10.0 MB/s eta 0:00:19\n",
      "   --- ------------------------------------ 19.7/204.2 MB 9.6 MB/s eta 0:00:20\n",
      "   ---- ----------------------------------- 20.4/204.2 MB 9.1 MB/s eta 0:00:21\n",
      "   ---- ----------------------------------- 20.4/204.2 MB 9.1 MB/s eta 0:00:21\n",
      "   ---- ----------------------------------- 20.7/204.2 MB 8.2 MB/s eta 0:00:23\n",
      "   ---- ----------------------------------- 20.7/204.2 MB 8.2 MB/s eta 0:00:23\n",
      "   ---- ----------------------------------- 20.7/204.2 MB 8.2 MB/s eta 0:00:23\n",
      "   ---- ----------------------------------- 21.2/204.2 MB 6.3 MB/s eta 0:00:29\n",
      "   ---- ----------------------------------- 21.5/204.2 MB 6.0 MB/s eta 0:00:31\n",
      "   ---- ----------------------------------- 22.0/204.2 MB 5.9 MB/s eta 0:00:31\n",
      "   ---- ----------------------------------- 22.5/204.2 MB 5.7 MB/s eta 0:00:32\n",
      "   ---- ----------------------------------- 22.5/204.2 MB 5.7 MB/s eta 0:00:32\n",
      "   ---- ----------------------------------- 23.1/204.2 MB 5.2 MB/s eta 0:00:35\n",
      "   ----- ---------------------------------- 26.5/204.2 MB 5.7 MB/s eta 0:00:32\n",
      "   ------ --------------------------------- 31.7/204.2 MB 6.5 MB/s eta 0:00:27\n",
      "   ------- -------------------------------- 36.4/204.2 MB 7.2 MB/s eta 0:00:24\n",
      "   ------- -------------------------------- 39.1/204.2 MB 7.4 MB/s eta 0:00:23\n",
      "   ------- -------------------------------- 39.6/204.2 MB 7.3 MB/s eta 0:00:23\n",
      "   ------- -------------------------------- 40.4/204.2 MB 7.1 MB/s eta 0:00:23\n",
      "   -------- ------------------------------- 41.4/204.2 MB 7.0 MB/s eta 0:00:24\n",
      "   -------- ------------------------------- 42.2/204.2 MB 7.0 MB/s eta 0:00:24\n",
      "   -------- ------------------------------- 43.3/204.2 MB 6.9 MB/s eta 0:00:24\n",
      "   -------- ------------------------------- 45.1/204.2 MB 6.9 MB/s eta 0:00:24\n",
      "   --------- ------------------------------ 46.9/204.2 MB 7.0 MB/s eta 0:00:23\n",
      "   --------- ------------------------------ 49.0/204.2 MB 7.0 MB/s eta 0:00:23\n",
      "   ---------- ----------------------------- 51.1/204.2 MB 7.1 MB/s eta 0:00:22\n",
      "   ---------- ----------------------------- 53.7/204.2 MB 7.3 MB/s eta 0:00:21\n",
      "   ---------- ----------------------------- 56.1/204.2 MB 7.4 MB/s eta 0:00:21\n",
      "   ----------- ---------------------------- 58.7/204.2 MB 7.5 MB/s eta 0:00:20\n",
      "   ------------ --------------------------- 61.3/204.2 MB 7.7 MB/s eta 0:00:19\n",
      "   ------------ --------------------------- 64.5/204.2 MB 7.8 MB/s eta 0:00:18\n",
      "   ------------- -------------------------- 67.4/204.2 MB 8.0 MB/s eta 0:00:18\n",
      "   -------------- ------------------------- 71.6/204.2 MB 8.2 MB/s eta 0:00:17\n",
      "   -------------- ------------------------- 75.2/204.2 MB 8.4 MB/s eta 0:00:16\n",
      "   -------------- ------------------------- 75.2/204.2 MB 8.4 MB/s eta 0:00:16\n",
      "   -------------- ------------------------- 75.8/204.2 MB 8.1 MB/s eta 0:00:16\n",
      "   -------------- ------------------------- 76.0/204.2 MB 8.0 MB/s eta 0:00:16\n",
      "   -------------- ------------------------- 76.5/204.2 MB 7.8 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 77.1/204.2 MB 7.8 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 77.9/204.2 MB 7.7 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 78.6/204.2 MB 7.6 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 80.0/204.2 MB 7.5 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 80.5/204.2 MB 7.5 MB/s eta 0:00:17\n",
      "   --------------- ------------------------ 81.5/204.2 MB 7.4 MB/s eta 0:00:17\n",
      "   ---------------- ----------------------- 82.6/204.2 MB 7.3 MB/s eta 0:00:17\n",
      "   ---------------- ----------------------- 83.6/204.2 MB 7.3 MB/s eta 0:00:17\n",
      "   ---------------- ----------------------- 84.4/204.2 MB 7.2 MB/s eta 0:00:17\n",
      "   ---------------- ----------------------- 86.2/204.2 MB 7.2 MB/s eta 0:00:17\n",
      "   ----------------- ---------------------- 88.1/204.2 MB 7.3 MB/s eta 0:00:16\n",
      "   ----------------- ---------------------- 89.7/204.2 MB 7.3 MB/s eta 0:00:16\n",
      "   ------------------ --------------------- 94.1/204.2 MB 7.5 MB/s eta 0:00:15\n",
      "   ------------------- -------------------- 98.6/204.2 MB 7.7 MB/s eta 0:00:14\n",
      "   ------------------- -------------------- 100.9/204.2 MB 7.8 MB/s eta 0:00:14\n",
      "   -------------------- ------------------- 103.5/204.2 MB 7.9 MB/s eta 0:00:13\n",
      "   -------------------- ------------------- 106.4/204.2 MB 8.0 MB/s eta 0:00:13\n",
      "   --------------------- ------------------ 109.3/204.2 MB 8.0 MB/s eta 0:00:12\n",
      "   --------------------- ------------------ 110.1/204.2 MB 8.0 MB/s eta 0:00:12\n",
      "   --------------------- ------------------ 111.7/204.2 MB 8.0 MB/s eta 0:00:12\n",
      "   ---------------------- ----------------- 112.5/204.2 MB 7.9 MB/s eta 0:00:12\n",
      "   ---------------------- ----------------- 114.8/204.2 MB 7.9 MB/s eta 0:00:12\n",
      "   ---------------------- ----------------- 116.7/204.2 MB 7.9 MB/s eta 0:00:12\n",
      "   ----------------------- ---------------- 120.3/204.2 MB 8.1 MB/s eta 0:00:11\n",
      "   ------------------------ --------------- 124.3/204.2 MB 8.2 MB/s eta 0:00:10\n",
      "   ------------------------- -------------- 128.5/204.2 MB 8.4 MB/s eta 0:00:10\n",
      "   ------------------------- -------------- 131.9/204.2 MB 8.5 MB/s eta 0:00:09\n",
      "   -------------------------- ------------- 134.5/204.2 MB 8.6 MB/s eta 0:00:09\n",
      "   -------------------------- ------------- 135.8/204.2 MB 8.6 MB/s eta 0:00:08\n",
      "   -------------------------- ------------- 136.6/204.2 MB 8.5 MB/s eta 0:00:08\n",
      "   -------------------------- ------------- 137.4/204.2 MB 8.4 MB/s eta 0:00:08\n",
      "   --------------------------- ------------ 138.1/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   --------------------------- ------------ 139.2/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   --------------------------- ------------ 140.2/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   --------------------------- ------------ 141.6/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   ---------------------------- ----------- 143.1/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   ---------------------------- ----------- 145.2/204.2 MB 8.3 MB/s eta 0:00:08\n",
      "   ---------------------------- ----------- 147.1/204.2 MB 8.3 MB/s eta 0:00:07\n",
      "   ----------------------------- ---------- 149.4/204.2 MB 8.3 MB/s eta 0:00:07\n",
      "   ----------------------------- ---------- 151.8/204.2 MB 8.3 MB/s eta 0:00:07\n",
      "   ------------------------------ --------- 153.6/204.2 MB 8.4 MB/s eta 0:00:07\n",
      "   ------------------------------ --------- 154.1/204.2 MB 8.3 MB/s eta 0:00:07\n",
      "   ------------------------------ --------- 154.7/204.2 MB 8.2 MB/s eta 0:00:07\n",
      "   ------------------------------ --------- 155.2/204.2 MB 8.2 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 155.7/204.2 MB 8.1 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 156.2/204.2 MB 8.1 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 156.8/204.2 MB 8.0 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 157.3/204.2 MB 7.9 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 157.5/204.2 MB 7.9 MB/s eta 0:00:06\n",
      "   ------------------------------ --------- 158.1/204.2 MB 7.8 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 158.6/204.2 MB 7.8 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 159.4/204.2 MB 7.7 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 159.9/204.2 MB 7.7 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 160.7/204.2 MB 7.6 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 161.0/204.2 MB 7.5 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 161.5/204.2 MB 7.5 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 162.0/204.2 MB 7.5 MB/s eta 0:00:06\n",
      "   ------------------------------- -------- 163.3/204.2 MB 7.4 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 164.4/204.2 MB 7.4 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 164.6/204.2 MB 7.4 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 165.2/204.2 MB 7.3 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 166.2/204.2 MB 7.3 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 166.7/204.2 MB 7.3 MB/s eta 0:00:06\n",
      "   -------------------------------- ------- 167.5/204.2 MB 7.2 MB/s eta 0:00:06\n",
      "   --------------------------------- ------ 168.6/204.2 MB 7.2 MB/s eta 0:00:05\n",
      "   --------------------------------- ------ 169.6/204.2 MB 7.2 MB/s eta 0:00:05\n",
      "   --------------------------------- ------ 169.6/204.2 MB 7.2 MB/s eta 0:00:05\n",
      "   --------------------------------- ------ 172.5/204.2 MB 7.2 MB/s eta 0:00:05\n",
      "   ---------------------------------- ----- 176.2/204.2 MB 7.2 MB/s eta 0:00:04\n",
      "   ----------------------------------- ---- 179.8/204.2 MB 7.3 MB/s eta 0:00:04\n",
      "   ------------------------------------ --- 183.8/204.2 MB 7.4 MB/s eta 0:00:03\n",
      "   ------------------------------------ --- 186.4/204.2 MB 7.5 MB/s eta 0:00:03\n",
      "   ------------------------------------ --- 188.0/204.2 MB 7.5 MB/s eta 0:00:03\n",
      "   ------------------------------------- -- 189.8/204.2 MB 7.5 MB/s eta 0:00:02\n",
      "   ------------------------------------- -- 191.6/204.2 MB 7.5 MB/s eta 0:00:02\n",
      "   ------------------------------------- -- 193.5/204.2 MB 7.5 MB/s eta 0:00:02\n",
      "   -------------------------------------- - 195.6/204.2 MB 7.5 MB/s eta 0:00:02\n",
      "   -------------------------------------- - 198.2/204.2 MB 7.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  200.8/204.2 MB 7.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.7/204.2 MB 7.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.9/204.2 MB 7.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------  203.9/204.2 MB 7.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 204.2/204.2 MB 7.5 MB/s eta 0:00:00\n",
      "Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)\n",
      "   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--\n",
      "   ---------------- ----------------------- 2.6/6.2 MB 12.5 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 6.0/6.2 MB 14.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.2/6.2 MB 13.5 MB/s eta 0:00:00\n",
      "Downloading torchvision-0.21.0-cp311-cp311-win_amd64.whl (1.6 MB)\n",
      "   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--\n",
      "   ---------------------------------------- 1.6/1.6 MB 13.8 MB/s eta 0:00:00\n",
      "Downloading torchaudio-2.6.0-cp311-cp311-win_amd64.whl (2.5 MB)\n",
      "   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--\n",
      "   ---------------------------------------- 2.5/2.5 MB 12.7 MB/s eta 0:00:00\n",
      "Installing collected packages: sympy, torch, torchvision, torchaudio\n",
      "  Attempting uninstall: sympy\n",
      "    Found existing installation: sympy 1.12\n",
      "    Uninstalling sympy-1.12:\n",
      "      Successfully uninstalled sympy-1.12\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 2.0.1\n",
      "    Uninstalling torch-2.0.1:\n",
      "      Successfully uninstalled torch-2.0.1\n",
      "  Attempting uninstall: torchvision\n",
      "    Found existing installation: torchvision 0.15.2\n",
      "    Uninstalling torchvision-0.15.2:\n",
      "      Successfully uninstalled torchvision-0.15.2\n",
      "Successfully installed sympy-1.13.1 torch-2.6.0 torchaudio-2.6.0 torchvision-0.21.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: Failed to remove contents in a temporary directory 'C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~orch'.\n",
      "  You can safely remove it manually.\n",
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "fastai 2.7.12 requires torch<2.1,>=1.7, but you have torch 2.6.0 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: transformers in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (4.50.0)\n",
      "Requirement already satisfied: filelock in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (3.12.4)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.29.3)\n",
      "Requirement already satisfied: numpy>=1.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (1.23.5)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (23.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (6.0.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2024.5.15)\n",
      "Requirement already satisfied: requests in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (2.32.3)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.21.1)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (0.4.3)\n",
      "Requirement already satisfied: tqdm>=4.27 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from transformers) (4.67.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2024.5.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)\n",
      "Requirement already satisfied: colorama in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tqdm>=4.27->transformers) (0.4.6)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\dell\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests->transformers) (2023.7.22)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade torch torchvision torchaudio\n",
    "!pip install --upgrade transformers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "87f5711f-61b9-4948-a132-ab52e1f97476",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "^C\n"
     ]
    }
   ],
   "source": [
    "!uvicorn main:app --host 127.0.0.3 --port 8000 --reload"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "9292ccec-fe9a-442a-9f33-a74d61fab72e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Device set to use cpu\n",
      "WARNING:  You must pass the application as an import string to enable 'reload' or 'workers'.\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import faiss\n",
    "import numpy as np\n",
    "import sqlite3\n",
    "import pandas as pd\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from fastapi import FastAPI, Body\n",
    "from pydantic import BaseModel\n",
    "import torch\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline\n",
    "import nest_asyncio\n",
    "import uvicorn\n",
    "\n",
    "# ✅ Initialize FastAPI\n",
    "app = FastAPI()\n",
    "\n",
    "# ✅ Load FAISS index & embeddings\n",
    "index = faiss.read_index(\"faiss_index.bin\")\n",
    "embeddings = np.load(\"embeddings.npy\")\n",
    "\n",
    "# ✅ Load dataset for reference\n",
    "df = pd.read_csv(\"data/processed_data.csv\")\n",
    "\n",
    "# ✅ Load Sentence Transformer for embedding generation\n",
    "model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
    "\n",
    "# ✅ Use Pretrained GPT Model for Answer Generation\n",
    "model_name = \"distilgpt2\"  # Replacing the non-existent \"gpt2-hotel-model\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "llm_model = AutoModelForCausalLM.from_pretrained(model_name)\n",
    "\n",
    "# ✅ Initialize the pipeline\n",
    "llm_pipeline = pipeline(\"text-generation\", model=llm_model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)\n",
    "\n",
    "# ✅ Define request model\n",
    "class QueryRequest(BaseModel):\n",
    "    query: str\n",
    "\n",
    "# ✅ Endpoint 1: Get Analytics from SQLite\n",
    "@app.post(\"/analytics\")\n",
    "def get_analytics():\n",
    "    conn = sqlite3.connect(\"hotel_analytics.db\")\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"SELECT * FROM analytics\")\n",
    "    results = {row[0]: row[1] for row in cursor.fetchall()}\n",
    "    conn.close()\n",
    "    return results\n",
    "\n",
    "# ✅ Endpoint 2: RAG-Powered Question Answering\n",
    "@app.post(\"/ask\")\n",
    "def ask_question(request: QueryRequest = Body(...)):\n",
    "    print(\"📥 Received Request:\", request)  # Debugging\n",
    "    print(\"🔍 Query Received:\", request.query)  # Debugging\n",
    "    \n",
    "    query = request.query\n",
    "    \n",
    "    # 🔍 Convert query to vector\n",
    "    query_embedding = model.encode([query], convert_to_numpy=True)\n",
    "    \n",
    "    # 🔍 Search FAISS index for relevant results\n",
    "    _, indices = index.search(query_embedding, 5)  # Top 5 similar entries\n",
    "    retrieved_texts = df.iloc[indices[0]][\"query_text\"].tolist()\n",
    "\n",
    "    # 🧠 Generate answer using Pretrained LLM\n",
    "    context = \" \".join(retrieved_texts)\n",
    "    input_text = f\"Context: {context} \\nQuestion: {query} \\nAnswer:\"\n",
    "    \n",
    "    generated_answer = llm_pipeline(input_text, max_length=100, num_return_sequences=1)[0][\"generated_text\"]\n",
    "    \n",
    "    return {\"retrieved_results\": retrieved_texts, \"generated_answer\": generated_answer}\n",
    "\n",
    "# ✅ Enable FastAPI to run inside Jupyter Notebook\n",
    "if __name__ == \"__main__\":\n",
    "    nest_asyncio.apply()\n",
    "    uvicorn.run(app, host=\"127.0.0.1\", port=8000, reload=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09cf9af2-9287-44f7-a20f-055b5e88745b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "response = requests.post(\"http://127.0.0.3:8000/ask\", json={\"query\": \"What is the total revenue?\"})\n",
    "print(response.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e40a0b7e-a86d-4e7a-a792-4bc50d217dba",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "'ps' is not recognized as an internal or external command,\n",
      "operable program or batch file.\n"
     ]
    }
   ],
   "source": [
    "!ps aux | grep 8000"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
